INSERT INTO tbl_cards (
    hp, pokemonName, type_id, stage_id, info, attack, damage, weak, resis, retreat, cardNumberInCollection, collection_id
)
VALUES
(50, 'Poliwag', 3, 1, 'Tadpole Pokémon', 'Water Gun', '10+', 'Lightning', '', '1', 59, 1),
(60, 'Poliwhirl', 3, 2, 'Tadpole Pokémon', 'Amnesia', '', 'Lightning', '', '2', 60, 1),
(90, 'Poliwrath', 3, 3, 'Tadpole Pokémon', 'Water Gun', '30+', 'Lightning', '', '3', 61, 1),
(70, 'Electabuzz', 4, 1, 'Electric Pokémon', 'Thunder Shock', '10', 'Fighting', 'Metal', '2', 20, 1),
(60, 'Magnemite', 4, 1, 'Magnet Pokémon', 'Thunder Wave', '10', 'Fighting', 'Metal', '1', 62, 1),
(70, 'Magneton', 4, 2, 'Magnet Pokémon', 'Selfdestruct', '80', 'Fighting', 'Metal', '3', 9, 1),
(40, 'Diglett', 6, 1, 'Mole Pokémon', 'Dig', '10', 'Grass', '', '1', 35, 1),
(60, 'Dugtrio', 6, 2, 'Mole Pokémon', 'Earthquake', '70', 'Grass', '', '2', 15, 1),
(50, 'Doduo', 7, 1, 'Twin Bird Pokémon', 'Fury Attack', '10x', 'Lightning', 'Fighting', '1', 36, 1),
(70, 'Dodrio', 7, 2, 'Triple Bird Pokémon', 'Rage', '10+', 'Lightning', 'Fighting', '2', 37, 1),
(60, 'Oddish', 1, 1, 'Weed Pokémon', 'Stun Spore', '10', 'Fire', '', '1', 43, 2),
(70, 'Gloom', 1, 2, 'Weed Pokémon', 'Poisonpowder', '20', 'Fire', '', '2', 44, 2),
(80, 'Vileplume', 1, 3, 'Flower Pokémon', 'Petal Dance', '40x', 'Fire', '', '3', 45, 2),
(50, 'Eevee', 7, 1, 'Evolution Pokémon', 'Tackle', '10', 'Fighting', 'Psychic', '1', 46, 2),
(70, 'Pidgeotto', 7, 2, 'Bird Pokémon', 'Whirlwind', '20', 'Lightning', 'Fighting', '1', 47, 2),
(90, 'Pidgeot', 7, 3, 'Bird Pokémon', 'Hurricane', '30', 'Lightning', 'Fighting', '2', 48, 2),
(60, 'Jigglypuff', 7, 1, 'Balloon Pokémon', 'Lullaby', '', 'Fighting', 'Psychic', '1', 49, 2),
(70, 'Dodrio', 7, 2, 'Triple Bird Pokémon', 'Rage', '10+', 'Lightning', 'Fighting', '2', 50, 2),
(80, 'Exeggcute', 1, 1, 'Egg Pokémon', 'Hypnosis', '', 'Fire', '', '1', 51, 2),
(90, 'Exeggutor', 1, 2, 'Coconut Pokémon', 'Teleport', '', 'Fire', '', '2', 52, 2),
(60, 'Zubat', 6, 1, 'Bat Pokémon', 'Leech Life', '10', 'Psychic', '', '1', 24, 3), 
(70, 'Golbat', 6, 2, 'Bat Pokémon', 'Wing Attack', '30', 'Psychic', '', '2', 25, 3), 
(80, 'Cloyster', 3, 2, 'Bivalve Pokémon', 'Clamp', '30', 'Lightning', '', '2', 26, 3), 
(60, 'Shellder', 3, 1, 'Bivalve Pokémon', 'Supersonic', '', 'Lightning', '', '1', 27, 3), 
(70, 'Krabby', 3, 1, 'River Crab Pokémon', 'Call for Family', '', 'Lightning', '', '1', 28, 3), 
(80, 'Kingler', 3, 2, 'Pincer Pokémon', 'Crabhammer', '40', 'Lightning', '', '2', 29, 3), 
(60, 'Slowpoke', 3, 1, 'Dopey Pokémon', 'Spacing Out', '', 'Lightning', '', '1', 30, 3), 
(80, 'Slowbro', 3, 2, 'Hermit Crab Pokémon', 'Headbutt', '20', 'Lightning', '', '2', 31, 3), 
(70, 'Hitmonlee', 6, 1, 'Kicking Pokémon', 'Stretch Kick', '30', 'Psychic', '', '1', 32, 3), 
(80, 'Machoke', 6, 2, 'Superpower Pokémon', 'Karate Chop', '50', 'Psychic', '', '2', 33, 3);